Create Meeting API- table contents
SCU-Projects/KatchUp pull request #13
Opened 2019-02-27 04:18 UTC by sushruth91

Added repository, services and controller.

2019-02-27 05:05 UTC, sivajrm requested changes

2019-02-27 05:05 UTC, sivajrm commented on src/main/java/com/app/katchup/Meeting/MeetingController.java
> +    @PostMapping("/meeting")
has to be meeting/create

2019-02-27 05:05 UTC, sivajrm commented on src/main/java/com/app/katchup/Meeting/MeetingController.java
> +        return new ResponseEntity<>(meeting, HttpStatus.OK);
HttpStatus.created

2019-02-27 05:05 UTC, sivajrm commented on src/main/java/com/app/katchup/Meeting/MeetingRepository.java
> +    @Query(value = "{'host' : ?0, 'startDateTime': ?2 , 'endDateTime':?3 , 'venue':?4}")
parameter numbering wrong. please take care

2019-02-27 05:05 UTC, sivajrm commented on src/main/java/com/app/katchup/Meeting/MeetingRepository.java
> +    Meeting findIfHostHasDuplicateMeeting(String host, LocalDateTime startDateTime, LocalDateTime endDateTime, String venue);
please rename to findMeetingByFilter

2019-02-27 05:05 UTC, sivajrm commented on src/main/java/com/app/katchup/Meeting/MeetingService.java
> +        if(meetingRepository.findIfHostHasDuplicateMeeting(meeting.getHost(),meeting.getStartDateTime(),meeting.getEndDateTime(),
please break it to two lines. update the method here based on the repository

2019-02-27 05:05 UTC, sivajrm commented on src/main/java/com/app/katchup/Meeting/MeetingService.java
> +        if(meetingRepository.findIfHostHasDuplicateMeeting(meeting.getHost(),meeting.getStartDateTime(),meeting.getEndDateTime(),
please watch for alignment in line#15

2019-02-27 05:05 UTC, sivajrm commented on src/main/java/com/app/katchup/Meeting/MeetingService.java
> +    public void createMeeting(Meeting meeting){
update the return type from void to Meeting object

2019-02-27 05:05 UTC, sivajrm commented on src/main/java/com/app/katchup/Meeting/MeetingController.java
> +        return new ResponseEntity<>(meeting, HttpStatus.OK);
get the returned meeting object from above line and return it along with responseentity

2019-02-27 05:34 UTC, sivajrm commented on src/main/java/com/app/katchup/Meeting/MeetingController.java
> +        return new ResponseEntity<>(meeting, HttpStatus.OK);
By default, you are returning meeeting object though the inside method returns some meeting for the host. This should not happen. You should get the response from the create meeting and check it if it is null, If it is null, return the error to the user if not return meeting created and the created object

2019-02-27 05:35 UTC, sivajrm commented on src/main/java/com/app/katchup/Meeting/MeetingService.java
> +        if(meetingRepository.findIfHostHasDuplicateMeeting(meeting.getHost(),meeting.getStartDateTime(),meeting.getEndDateTime(),
Return null if there exists a meeting already if not, go ahead and call save(), then get the same meeting to verify the insertion is successful and then return that object to the controller.

2019-02-27 05:59 UTC, sivajrm commented on src/main/java/com/app/katchup/Meeting/MeetingService.java
> +        return meeting;
if the condition is true, save it to the meeting and get the same meeting from DB then only the user will know the meeting-id and meeting pwd. 
if condition is false, return null

2019-02-27 06:01 UTC, sivajrm commented on src/main/java/com/app/katchup/Meeting/MeetingService.java
> +        return meeting;
Another option, put the application in debugger and show me the pwd and meeting id without getting the same meeting from DB. If this is possible, you dont need to do the DB fetching again.

2019-02-27 06:02 UTC, sivajrm commented on src/main/java/com/app/katchup/Meeting/model/Meeting.java
> +import javax.xml.ws.Response;
Where is this used ?

2019-02-27 06:03 UTC, sivajrm requested changes
Please take care of the comments of the latest commit

2019-02-27 17:39 UTC, sushruth91 commented
Updated return types

2019-02-27 19:34 UTC, sivajrm commented on src/main/java/com/app/katchup/Meeting/model/Meeting.java
> -    private Status status;
What happenned to Status?

2019-02-27 19:34 UTC, sivajrm commented on src/main/java/com/app/katchup/Meeting/model/Meeting.java
> +import javax.xml.ws.Response;
please answer here

2019-02-27 19:37 UTC, sivajrm commented on src/main/java/com/app/katchup/Meeting/MeetingController.java
> +        return new ResponseEntity<>(meetingCreated, HttpStatus.CREATED);
please add null check for the returned object, if it is null, HttpStatus.Conflict(409)
else created

2019-02-27 22:53 UTC, sushruth91 commented
Added null checker.

2019-02-28 01:35 UTC, sushruth91 commented
Added null checker

2019-02-28 01:46 UTC, sivajrm approved these changes
With /meeting/create api

2019-02-28 02:33 UTC, sivajrm approved these changes

2019-02-28 02:33 UTC, merged